import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
const leagueSpartan = League_Spartan({ weight: '400', subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Skycaptain - Fly over",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={leagueSpartan.className}>
      {children}
      <Toaster />
      </body>
    </html>
  );
}
